export const REGISTER = 'USERNAME_REGISTER';
export const REGISTER_START = 'USERNAME_REGISTER_START';
export const REGISTER_ERROR = 'USERNAME_REGISTER_ERROR';
export const REGISTER_SUCCESS = 'USERNAME_REGISTER_SUCCESS';

export const MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_START = 'SEND_MESSAGE_START';
export const MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

export const HISTORY = 'USER_GETHISTORY';

export const LEAVE = 'USER_LEAVE';
export const LEAVE_SUCCESS = 'LEAVE_SUCCESS';